services:
    api:
      container_name: api
      build:
        context: .
        dockerfile: api/Dockerfile.api
      image: mutcompute-api
      ports:
        - "5000:5000"
      volumes:
        - ./api:/app/
      environment: 
        - MAIL_SERVER=email
        - MAIL_PORT=8025
      command: gunicorn -b 0.0.0.0:5000 api:app
    client:
      container_name: client
      build:
        context: .
        dockerfile: client/Dockerfile.client
      image: mutcompute-client
      ports:
        - "3000:3000"
      volumes:
        - ./client:/app/
    email:
      container_name: email
      build:
        context: .
        dockerfile: api/Dockerfile.api
      image: mutcompute-api
      ports:
        - "8025:8025"
      command: python -m smtpd -n -c DebuggingServer 0.0.0.0:8025
    db:
      image: postgres:13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: mutcompute
        POSTGRES_PASSWORD: mutcompute
        POSTGRES_DB: mutcompute_dev
      networks:
        - default
      ports:
        - 5405:5432
      restart: always
      volumes:
        - ./postgres-data:/var/lib/postgresql/data 

      