services:
    api:
      container_name: api
      build:
        context: ./api
        dockerfile: Dockerfile.api
      image: mutcompute-api
      ports:
        - "5000:5000"
      volumes:
        - ./api:/app/
      environment: 
        - MAIL_SERVER=email
        - MAIL_PORT=8025
      command: gunicorn -b 0.0.0.0:5000 api:app
    client:
      container_name: client
      build:
        context: ./client
        dockerfile: Dockerfile.client
      image: mutcompute-client
      ports:
        - "3000:3000"
      # volumes:
      #   - ./client:/app/
      command: yarn start
    # email:
    #   container_name: email
    #   build:
    #     context: ./api
    #     dockerfile: Dockerfile.api
    #   image: mutcompute-api
    #   ports:
    #     - "8025:8025"
    #   command: python -m smtpd -n -c DebuggingServer 0.0.0.0:8025 

      