services:
    api:
      build:
        context: .
        dockerfile: Dockerfile.api
      image: mutcompute-api
    client:
      build:
        context: .
        dockerfile: Dockerfile.client
      image: mutcompute-client
      ports:
        - "3000:3000"