services:
    api:
      build:
        context: .
        dockerfile: api/Dockerfile.api
      image: mutcompute-api
      ports:
        - "5000:5000"
      volumes:
        - ./api:/app/
      command: gunicorn -b 0.0.0.0:5000 api:app
    client:
      build:
        context: .
        dockerfile: client/Dockerfile.client
      image: mutcompute-client
      ports:
        - "3000:3000"
      volumes:
        - ./client:/app/

      